theme = "dracula"

[editor]
line-number = "relative"
auto-completion = true
auto-info = true
completion-trigger-len = 2
true-color = true
shell = ["zsh", "-c"]
color-modes = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NOR"
mode.insert = "INS"
mode.select = "SEL"

[editor.cursor-shape]
insert = "bar"
normal = "underline"
select = "underline"

[editor.file-picker]
hidden = true
git-global = true
git-ignore = true
parents = true

[editor.lsp]
display-messages = true

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[editor.search]
smart-case = true
wrap-around = true
