# Leptos
[[language]]
name = "rust"

[language-server.rust-analyzer]
config = { procMacro = { ignored = { leptos_macro = ["server"] } } }

# Typst
[language-server.tinymist]
command = "tinymist"

[[language]]
name = "typst"
language-servers = ["tinymist"]

# Go
[[languages]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

# PyLsp
[[language]]
name = "python"
language-servers = ["pylsp"]

[language-server.pylsp.config.pylsp]
plugins.pyls_mypy.enabled = true
plugins.pyls_mypy.live_mode = true

# Astro
[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = {typescript = {tsdk = "/Users/user/.bun/install/global/node_modules/typescript/lib"}, environment = "node"}

[[language]]
name = "astro"
auto-format = true
language-servers = [ "astro-ls" ]

# TOML
[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

# Yaml
[language-server.yaml-language-server.config.yaml]
format = { enable = true }
validation = true

# Json
config = { "provideFormatter" = true, "json" = { "keepLines" = { "enable" = true } } }

# Tailwind
[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]

# CSS
[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]

# JSX
[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

# TSX
[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

# Svelte
[[language]]
name = "svelte"
language-servers = [ "svelteserver", "tailwindcss-ls" ]

# SQL
[language-server.sql-language-server]
command = "sql-language-server"
args = ["up", "--method", "stdio"]

[[language]]
name = "sql"
language-servers = [ "sql-language-server" ]
